import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hagz_kora/core/router/app_router.dart';
import 'package:hagz_kora/core/theme/app_theme.dart';

// TODO(phase0): restore after `flutter pub get` generates l10n files
// import 'package:flutter_gen/gen_l10n/app_localizations.dart';

/// Root widget that wires together routing, localizations, and theme.
///
/// Consumed by both [main_dev.dart] and [main_prod.dart] via [ProviderScope].
class HagzKoraApp extends ConsumerWidget {
  const HagzKoraApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // appRouterProvider is generated by riverpod_generator.
    // Run `dart run build_runner build` to generate app_router.g.dart.
    final router = ref.watch(appRouterProvider);

    return MaterialApp.router(
      title: 'Hagz Kora',
      debugShowCheckedModeBanner: false,

      // Routing
      routerConfig: router,

      // Theme
      theme: AppTheme.light,

      // Localization — AppLocalizations.delegate added after l10n gen
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('ar'), // Arabic — RTL, primary locale
        Locale('en'), // English
      ],
      locale: const Locale('ar'),
    );
  }
}
